services:
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=testdb
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db-data:

